
server:
  port: 3333
#注意application-name(配置文件前缀)需要对应git仓库中 config-client-dev、config-client-test、config-client-prod为名称的配置文件
spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    host: localhost
  application:
    name: config-cloud-client
  cloud:
    config:
      #指定当前所属环境
      profile: dev
      discovery:
        #开启通过服务访问config-cloud-server的功能
        enabled: true
        #指定配置中心注册到eureka的serviceId(即config-cloud-server的application-name)
        serviceId: config-cloud-server
      #git仓库分支
      label: testcloud1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  cloudfoundry:
    enabled: false
#忽略权限拦截